In [64]:
import sklearn
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier
import sklearn.metrics as metrics
from sklearn import datasets
from sklearn import svm
import pandas as pd
import numpy as np

In [65]:
cancer = datasets.load_breast_cancer()

In [66]:
#print(cancer.feature_names)
#print(cancer.target_names)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
['malignant' 'benign']


In [67]:
x = cancer.data
y = cancer.target

In [68]:
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size = 0.2)

In [69]:
print(x_train, y_train)

[[1.546e+01 1.948e+01 1.017e+02 ... 1.514e-01 2.837e-01 8.019e-02]
 [1.049e+01 1.929e+01 6.741e+01 ... 3.203e-02 2.826e-01 7.552e-02]
 [1.051e+01 2.019e+01 6.864e+01 ... 6.136e-02 2.383e-01 9.026e-02]
 ...
 [1.315e+01 1.534e+01 8.531e+01 ... 9.722e-02 3.849e-01 8.633e-02]
 [1.161e+01 1.602e+01 7.546e+01 ... 1.105e-01 2.787e-01 7.427e-02]
 [1.020e+01 1.748e+01 6.505e+01 ... 3.571e-02 2.868e-01 7.809e-02]] [0 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1
 0 1 0 0 0 0 1 1 1 1 0 1 0 0 1 0 0 1 1 1 0 1 1 1 1 0 0 1 1 0 0 0 1 1 1 0 1
 0 0 0 1 1 1 1 1 1 1 0 0 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 1 0 1 0 0 0 1
 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 1
 0 0 1 1 1 1 1 0 0 1 1 0 0 1 0 0 0 1 0 1 1 1 1 0 0 0 1 1 0 1 0 1 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 0 1 0 1 0
 0 1 1 1 1 1 0 0 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 1 0 

In [70]:
classes = ['malignant', 'benign']

In [74]:
#clf = svm.SVC(kernel="poly", C=1)
clf = KNeighborsClassifier(n_neighbors = 13)
clf.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=13)

In [75]:
y_pred = clf.predict(x_test)

In [76]:
acc = metrics.accuracy_score(y_test, y_pred)

In [77]:
print(acc)

0.9122807017543859
